package types

type Oi4Data struct {
	PrimaryValue      interface{} `json:"Pv"`
	SecondaryValue1   interface{} `json:"Sv1,omitempty"`
	SecondaryValue2   interface{} `json:"Sv2,omitempty"`
	SecondaryValue3   interface{} `json:"Sv3,omitempty"`
	SecondaryValue4   interface{} `json:"Sv4,omitempty"`
	SecondaryValue5   interface{} `json:"Sv5,omitempty"`
	SecondaryValue6   interface{} `json:"Sv6,omitempty"`
	SecondaryValue7   interface{} `json:"Sv7,omitempty"`
	SecondaryValue8   interface{} `json:"Sv8,omitempty"`
	SecondaryValue9   interface{} `json:"Sv9,omitempty"`
	SecondaryValue10  interface{} `json:"Sv10,omitempty"`
	SecondaryValue11  interface{} `json:"Sv11,omitempty"`
	SecondaryValue12  interface{} `json:"Sv12,omitempty"`
	SecondaryValue13  interface{} `json:"Sv13,omitempty"`
	SecondaryValue14  interface{} `json:"Sv14,omitempty"`
	SecondaryValue15  interface{} `json:"Sv15,omitempty"`
	SecondaryValue16  interface{} `json:"Sv16,omitempty"`
	SecondaryValue17  interface{} `json:"Sv17,omitempty"`
	SecondaryValue18  interface{} `json:"Sv18,omitempty"`
	SecondaryValue19  interface{} `json:"Sv19,omitempty"`
	SecondaryValue20  interface{} `json:"Sv20,omitempty"`
	SecondaryValue21  interface{} `json:"Sv21,omitempty"`
	SecondaryValue22  interface{} `json:"Sv22,omitempty"`
	SecondaryValue23  interface{} `json:"Sv23,omitempty"`
	SecondaryValue24  interface{} `json:"Sv24,omitempty"`
	SecondaryValue25  interface{} `json:"Sv25,omitempty"`
	SecondaryValue26  interface{} `json:"Sv26,omitempty"`
	SecondaryValue27  interface{} `json:"Sv27,omitempty"`
	SecondaryValue28  interface{} `json:"Sv28,omitempty"`
	SecondaryValue29  interface{} `json:"Sv29,omitempty"`
	SecondaryValue30  interface{} `json:"Sv30,omitempty"`
	SecondaryValue31  interface{} `json:"Sv31,omitempty"`
	SecondaryValue32  interface{} `json:"Sv32,omitempty"`
	SecondaryValue33  interface{} `json:"Sv33,omitempty"`
	SecondaryValue34  interface{} `json:"Sv34,omitempty"`
	SecondaryValue35  interface{} `json:"Sv35,omitempty"`
	SecondaryValue36  interface{} `json:"Sv36,omitempty"`
	SecondaryValue37  interface{} `json:"Sv37,omitempty"`
	SecondaryValue38  interface{} `json:"Sv38,omitempty"`
	SecondaryValue39  interface{} `json:"Sv39,omitempty"`
	SecondaryValue40  interface{} `json:"Sv40,omitempty"`
	SecondaryValue41  interface{} `json:"Sv41,omitempty"`
	SecondaryValue42  interface{} `json:"Sv42,omitempty"`
	SecondaryValue43  interface{} `json:"Sv43,omitempty"`
	SecondaryValue44  interface{} `json:"Sv44,omitempty"`
	SecondaryValue45  interface{} `json:"Sv45,omitempty"`
	SecondaryValue46  interface{} `json:"Sv46,omitempty"`
	SecondaryValue47  interface{} `json:"Sv47,omitempty"`
	SecondaryValue48  interface{} `json:"Sv48,omitempty"`
	SecondaryValue49  interface{} `json:"Sv49,omitempty"`
	SecondaryValue50  interface{} `json:"Sv50,omitempty"`
	SecondaryValue51  interface{} `json:"Sv51,omitempty"`
	SecondaryValue52  interface{} `json:"Sv52,omitempty"`
	SecondaryValue53  interface{} `json:"Sv53,omitempty"`
	SecondaryValue54  interface{} `json:"Sv54,omitempty"`
	SecondaryValue55  interface{} `json:"Sv55,omitempty"`
	SecondaryValue56  interface{} `json:"Sv56,omitempty"`
	SecondaryValue57  interface{} `json:"Sv57,omitempty"`
	SecondaryValue58  interface{} `json:"Sv58,omitempty"`
	SecondaryValue59  interface{} `json:"Sv59,omitempty"`
	SecondaryValue60  interface{} `json:"Sv60,omitempty"`
	SecondaryValue61  interface{} `json:"Sv61,omitempty"`
	SecondaryValue62  interface{} `json:"Sv62,omitempty"`
	SecondaryValue63  interface{} `json:"Sv63,omitempty"`
	SecondaryValue64  interface{} `json:"Sv64,omitempty"`
	SecondaryValue65  interface{} `json:"Sv65,omitempty"`
	SecondaryValue66  interface{} `json:"Sv66,omitempty"`
	SecondaryValue67  interface{} `json:"Sv67,omitempty"`
	SecondaryValue68  interface{} `json:"Sv68,omitempty"`
	SecondaryValue69  interface{} `json:"Sv69,omitempty"`
	SecondaryValue70  interface{} `json:"Sv70,omitempty"`
	SecondaryValue71  interface{} `json:"Sv71,omitempty"`
	SecondaryValue72  interface{} `json:"Sv72,omitempty"`
	SecondaryValue73  interface{} `json:"Sv73,omitempty"`
	SecondaryValue74  interface{} `json:"Sv74,omitempty"`
	SecondaryValue75  interface{} `json:"Sv75,omitempty"`
	SecondaryValue76  interface{} `json:"Sv76,omitempty"`
	SecondaryValue77  interface{} `json:"Sv77,omitempty"`
	SecondaryValue78  interface{} `json:"Sv78,omitempty"`
	SecondaryValue79  interface{} `json:"Sv79,omitempty"`
	SecondaryValue80  interface{} `json:"Sv80,omitempty"`
	SecondaryValue81  interface{} `json:"Sv81,omitempty"`
	SecondaryValue82  interface{} `json:"Sv82,omitempty"`
	SecondaryValue83  interface{} `json:"Sv83,omitempty"`
	SecondaryValue84  interface{} `json:"Sv84,omitempty"`
	SecondaryValue85  interface{} `json:"Sv85,omitempty"`
	SecondaryValue86  interface{} `json:"Sv86,omitempty"`
	SecondaryValue87  interface{} `json:"Sv87,omitempty"`
	SecondaryValue88  interface{} `json:"Sv88,omitempty"`
	SecondaryValue89  interface{} `json:"Sv89,omitempty"`
	SecondaryValue90  interface{} `json:"Sv90,omitempty"`
	SecondaryValue91  interface{} `json:"Sv91,omitempty"`
	SecondaryValue92  interface{} `json:"Sv92,omitempty"`
	SecondaryValue93  interface{} `json:"Sv93,omitempty"`
	SecondaryValue94  interface{} `json:"Sv94,omitempty"`
	SecondaryValue95  interface{} `json:"Sv95,omitempty"`
	SecondaryValue96  interface{} `json:"Sv96,omitempty"`
	SecondaryValue97  interface{} `json:"Sv97,omitempty"`
	SecondaryValue98  interface{} `json:"Sv98,omitempty"`
	SecondaryValue99  interface{} `json:"Sv99,omitempty"`
	SecondaryValue100 interface{} `json:"Sv100,omitempty"`
	SecondaryValue101 interface{} `json:"Sv101,omitempty"`
	SecondaryValue102 interface{} `json:"Sv102,omitempty"`
	SecondaryValue103 interface{} `json:"Sv103,omitempty"`
	SecondaryValue104 interface{} `json:"Sv104,omitempty"`
	SecondaryValue105 interface{} `json:"Sv105,omitempty"`
	SecondaryValue106 interface{} `json:"Sv106,omitempty"`
	SecondaryValue107 interface{} `json:"Sv107,omitempty"`
	SecondaryValue108 interface{} `json:"Sv108,omitempty"`
	SecondaryValue109 interface{} `json:"Sv109,omitempty"`
	SecondaryValue110 interface{} `json:"Sv110,omitempty"`
	SecondaryValue111 interface{} `json:"Sv111,omitempty"`
	SecondaryValue112 interface{} `json:"Sv112,omitempty"`
	SecondaryValue113 interface{} `json:"Sv113,omitempty"`
	SecondaryValue114 interface{} `json:"Sv114,omitempty"`
	SecondaryValue115 interface{} `json:"Sv115,omitempty"`
	SecondaryValue116 interface{} `json:"Sv116,omitempty"`
	SecondaryValue117 interface{} `json:"Sv117,omitempty"`
	SecondaryValue118 interface{} `json:"Sv118,omitempty"`
	SecondaryValue119 interface{} `json:"Sv119,omitempty"`
	SecondaryValue120 interface{} `json:"Sv120,omitempty"`
	SecondaryValue121 interface{} `json:"Sv121,omitempty"`
	SecondaryValue122 interface{} `json:"Sv122,omitempty"`
	SecondaryValue123 interface{} `json:"Sv123,omitempty"`
	SecondaryValue124 interface{} `json:"Sv124,omitempty"`
	SecondaryValue125 interface{} `json:"Sv125,omitempty"`
	SecondaryValue126 interface{} `json:"Sv126,omitempty"`
	SecondaryValue127 interface{} `json:"Sv127,omitempty"`
	SecondaryValue128 interface{} `json:"Sv128,omitempty"`
	SecondaryValue129 interface{} `json:"Sv129,omitempty"`
	SecondaryValue130 interface{} `json:"Sv130,omitempty"`
	SecondaryValue131 interface{} `json:"Sv131,omitempty"`
	SecondaryValue132 interface{} `json:"Sv132,omitempty"`
	SecondaryValue133 interface{} `json:"Sv133,omitempty"`
	SecondaryValue134 interface{} `json:"Sv134,omitempty"`
	SecondaryValue135 interface{} `json:"Sv135,omitempty"`
	SecondaryValue136 interface{} `json:"Sv136,omitempty"`
	SecondaryValue137 interface{} `json:"Sv137,omitempty"`
	SecondaryValue138 interface{} `json:"Sv138,omitempty"`
	SecondaryValue139 interface{} `json:"Sv139,omitempty"`
	SecondaryValue140 interface{} `json:"Sv140,omitempty"`
	SecondaryValue141 interface{} `json:"Sv141,omitempty"`
	SecondaryValue142 interface{} `json:"Sv142,omitempty"`
	SecondaryValue143 interface{} `json:"Sv143,omitempty"`
	SecondaryValue144 interface{} `json:"Sv144,omitempty"`
	SecondaryValue145 interface{} `json:"Sv145,omitempty"`
	SecondaryValue146 interface{} `json:"Sv146,omitempty"`
	SecondaryValue147 interface{} `json:"Sv147,omitempty"`
	SecondaryValue148 interface{} `json:"Sv148,omitempty"`
	SecondaryValue149 interface{} `json:"Sv149,omitempty"`
	SecondaryValue150 interface{} `json:"Sv150,omitempty"`
	SecondaryValue151 interface{} `json:"Sv151,omitempty"`
	SecondaryValue152 interface{} `json:"Sv152,omitempty"`
	SecondaryValue153 interface{} `json:"Sv153,omitempty"`
	SecondaryValue154 interface{} `json:"Sv154,omitempty"`
	SecondaryValue155 interface{} `json:"Sv155,omitempty"`
	SecondaryValue156 interface{} `json:"Sv156,omitempty"`
	SecondaryValue157 interface{} `json:"Sv157,omitempty"`
	SecondaryValue158 interface{} `json:"Sv158,omitempty"`
	SecondaryValue159 interface{} `json:"Sv159,omitempty"`
	SecondaryValue160 interface{} `json:"Sv160,omitempty"`
	SecondaryValue161 interface{} `json:"Sv161,omitempty"`
	SecondaryValue162 interface{} `json:"Sv162,omitempty"`
	SecondaryValue163 interface{} `json:"Sv163,omitempty"`
	SecondaryValue164 interface{} `json:"Sv164,omitempty"`
	SecondaryValue165 interface{} `json:"Sv165,omitempty"`
	SecondaryValue166 interface{} `json:"Sv166,omitempty"`
	SecondaryValue167 interface{} `json:"Sv167,omitempty"`
	SecondaryValue168 interface{} `json:"Sv168,omitempty"`
	SecondaryValue169 interface{} `json:"Sv169,omitempty"`
	SecondaryValue170 interface{} `json:"Sv170,omitempty"`
	SecondaryValue171 interface{} `json:"Sv171,omitempty"`
	SecondaryValue172 interface{} `json:"Sv172,omitempty"`
	SecondaryValue173 interface{} `json:"Sv173,omitempty"`
	SecondaryValue174 interface{} `json:"Sv174,omitempty"`
	SecondaryValue175 interface{} `json:"Sv175,omitempty"`
	SecondaryValue176 interface{} `json:"Sv176,omitempty"`
	SecondaryValue177 interface{} `json:"Sv177,omitempty"`
	SecondaryValue178 interface{} `json:"Sv178,omitempty"`
	SecondaryValue179 interface{} `json:"Sv179,omitempty"`
	SecondaryValue180 interface{} `json:"Sv180,omitempty"`
	SecondaryValue181 interface{} `json:"Sv181,omitempty"`
	SecondaryValue182 interface{} `json:"Sv182,omitempty"`
	SecondaryValue183 interface{} `json:"Sv183,omitempty"`
	SecondaryValue184 interface{} `json:"Sv184,omitempty"`
	SecondaryValue185 interface{} `json:"Sv185,omitempty"`
	SecondaryValue186 interface{} `json:"Sv186,omitempty"`
	SecondaryValue187 interface{} `json:"Sv187,omitempty"`
	SecondaryValue188 interface{} `json:"Sv188,omitempty"`
	SecondaryValue189 interface{} `json:"Sv189,omitempty"`
	SecondaryValue190 interface{} `json:"Sv190,omitempty"`
	SecondaryValue191 interface{} `json:"Sv191,omitempty"`
	SecondaryValue192 interface{} `json:"Sv192,omitempty"`
	SecondaryValue193 interface{} `json:"Sv193,omitempty"`
	SecondaryValue194 interface{} `json:"Sv194,omitempty"`
	SecondaryValue195 interface{} `json:"Sv195,omitempty"`
	SecondaryValue196 interface{} `json:"Sv196,omitempty"`
	SecondaryValue197 interface{} `json:"Sv197,omitempty"`
	SecondaryValue198 interface{} `json:"Sv198,omitempty"`
	SecondaryValue199 interface{} `json:"Sv199,omitempty"`
	SecondaryValue200 interface{} `json:"Sv200,omitempty"`
	SecondaryValue201 interface{} `json:"Sv201,omitempty"`
	SecondaryValue202 interface{} `json:"Sv202,omitempty"`
	SecondaryValue203 interface{} `json:"Sv203,omitempty"`
	SecondaryValue204 interface{} `json:"Sv204,omitempty"`
	SecondaryValue205 interface{} `json:"Sv205,omitempty"`
	SecondaryValue206 interface{} `json:"Sv206,omitempty"`
	SecondaryValue207 interface{} `json:"Sv207,omitempty"`
	SecondaryValue208 interface{} `json:"Sv208,omitempty"`
	SecondaryValue209 interface{} `json:"Sv209,omitempty"`
	SecondaryValue210 interface{} `json:"Sv210,omitempty"`
	SecondaryValue211 interface{} `json:"Sv211,omitempty"`
	SecondaryValue212 interface{} `json:"Sv212,omitempty"`
	SecondaryValue213 interface{} `json:"Sv213,omitempty"`
	SecondaryValue214 interface{} `json:"Sv214,omitempty"`
	SecondaryValue215 interface{} `json:"Sv215,omitempty"`
	SecondaryValue216 interface{} `json:"Sv216,omitempty"`
	SecondaryValue217 interface{} `json:"Sv217,omitempty"`
	SecondaryValue218 interface{} `json:"Sv218,omitempty"`
	SecondaryValue219 interface{} `json:"Sv219,omitempty"`
	SecondaryValue220 interface{} `json:"Sv220,omitempty"`
	SecondaryValue221 interface{} `json:"Sv221,omitempty"`
	SecondaryValue222 interface{} `json:"Sv222,omitempty"`
	SecondaryValue223 interface{} `json:"Sv223,omitempty"`
	SecondaryValue224 interface{} `json:"Sv224,omitempty"`
	SecondaryValue225 interface{} `json:"Sv225,omitempty"`
	SecondaryValue226 interface{} `json:"Sv226,omitempty"`
	SecondaryValue227 interface{} `json:"Sv227,omitempty"`
	SecondaryValue228 interface{} `json:"Sv228,omitempty"`
	SecondaryValue229 interface{} `json:"Sv229,omitempty"`
	SecondaryValue230 interface{} `json:"Sv230,omitempty"`
	SecondaryValue231 interface{} `json:"Sv231,omitempty"`
	SecondaryValue232 interface{} `json:"Sv232,omitempty"`
	SecondaryValue233 interface{} `json:"Sv233,omitempty"`
	SecondaryValue234 interface{} `json:"Sv234,omitempty"`
	SecondaryValue235 interface{} `json:"Sv235,omitempty"`
	SecondaryValue236 interface{} `json:"Sv236,omitempty"`
	SecondaryValue237 interface{} `json:"Sv237,omitempty"`
	SecondaryValue238 interface{} `json:"Sv238,omitempty"`
	SecondaryValue239 interface{} `json:"Sv239,omitempty"`
	SecondaryValue240 interface{} `json:"Sv240,omitempty"`
	SecondaryValue241 interface{} `json:"Sv241,omitempty"`
	SecondaryValue242 interface{} `json:"Sv242,omitempty"`
	SecondaryValue243 interface{} `json:"Sv243,omitempty"`
	SecondaryValue244 interface{} `json:"Sv244,omitempty"`
	SecondaryValue245 interface{} `json:"Sv245,omitempty"`
	SecondaryValue246 interface{} `json:"Sv246,omitempty"`
	SecondaryValue247 interface{} `json:"Sv247,omitempty"`
	SecondaryValue248 interface{} `json:"Sv248,omitempty"`
	SecondaryValue249 interface{} `json:"Sv249,omitempty"`
	SecondaryValue250 interface{} `json:"Sv250,omitempty"`
	SecondaryValue251 interface{} `json:"Sv251,omitempty"`
	SecondaryValue252 interface{} `json:"Sv252,omitempty"`
	SecondaryValue253 interface{} `json:"Sv253,omitempty"`
	SecondaryValue254 interface{} `json:"Sv254,omitempty"`
	SecondaryValue255 interface{} `json:"Sv255,omitempty"`
}
