name: release-snapshot

env:
  CI: true
on:
  push:
    branches:
      - development
    tags:
      - "!*"
jobs:
  release:
    name: Setup and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - run: go version
      - name: Prepare Docker build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          make docker_prepare
          docker buildx inspect --bootstrap
      - name: Docker Build & Push
        run:  |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 -t oi4a/oi4-oec-service-demo-golang:0.1.0 -t oi4a/oi4-oec-service-demo-golang:latest .
        env:
          GO111MODULE: on
